apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-factory-app
spec:
  replicas: 3
  revisionHistoryLimit: 3  # <--- Questo pulirÃ  i ReplicaSet in eccesso su ArgoCD
  selector:
    matchLabels:
      app: data-factory
  template:
    metadata:
      labels:
        app: data-factory
    spec:
      containers:
      - name: app
        image: giacomo12305/data-factory-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "data_factory_db"
        - name: DB_USER
          value: "admin"
        - name: DB_PASS
          value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: data-factory-service
spec:
  selector:
    app: data-factory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
