apiVersion: v1
kind: Namespace
metadata:
  name: data-factory-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: data-factory-app
data:
  # L'indirizzo completo permette all'app di "uscire" dal suo namespace
  # e trovare il database in data-factory-db
  DB_HOST: "postgres.data-factory-db.svc.cluster.local"
  DB_NAME: "data_factory_db"
  DB_USER: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: data-factory-app
type: Opaque
stringData:
  DB_PASS: "password"
