apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-factory-app
  namespace: data-factory-app # Spostiamo il Deployment qui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: data-factory
  template:
    metadata:
      labels:
        app: data-factory
    spec:
      containers:
      - name: app
        image: giacomo12305/data-factory-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config # Lo trova perché è nello stesso namespace
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            configMapKeyRef:
              name: app-secrets
              key: DB_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: data-factory-service
  namespace: data-factory-app # Anche il servizio deve stare qui
spec:
  selector:
    app: data-factory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
