apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-factory-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # Se usi K3s di default, a volte la classe è "traefik", ma nginx è lo standard
spec:
  rules:
  - host: data-factory.192.168.64.2.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: data-factory-service
            port:
              number: 80
