apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-factory-ingress
  namespace: data-factory-app  # Deve essere lo stesso del Service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: data-factory.192.168.64.2.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: data-factory-service
            port:
              number: 80
