apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: data-factory-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.64.100-192.168.64.105
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: data-factory-advertisement
  namespace: metallb-system
